# ~/.bash_profile
#每个用户都可使用该文件输入专用于自己使用的shell信息,当用户登录时,该文件仅仅执行一次!默认情况下,他设置一些环境变量,执行用户的.bashrc文件。这里是推荐放置个人设置的地方
#

#执行./bashrc文件
[[ -f ~/.bashrc ]] && . ~/.bashrc 



LD_LIBRARY_PATH=/opt/cuda/lib64
export LD_LIBRARY_PATH



